### ISSUE TITLE
CRITICAL:type:can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by namsor** [namsor/namsor-python-tools-v2#1]
Fails with error 
CRITICAL:type:can only concatenate str (not "NoneType") to str
when processing a line like: 
31884|9|5|GR
or
31884|JOHN|.|GR

Workaround : remove the line.

**Comment by Oshan96** [comment]
Has this been fixed?

**Comment by namsor** [comment]
Hi @Oshan96,
Sorry, no not yet, but there is a rather simple workaround. But we should fix it, it's an easy one. I've put someone on it. 
Thanks for the reminder !

**Comment by Oshan96** [comment]
Oh, I was about to take a look at it and send a pull request with possible fixes. If someone is working on it there's no need.

You're welcome!

**Comment by namsor** [comment]
Hi! This bug has been resolved.
